apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
        - name: ecomm
          image: shanthaveer/react-apk:latest
          ports:
            - containerPort: 80
